### ISSUE TITLE
(Question) Any plans to backport this to older versions?

### ISSUE THREAD

**Issue by Cosmiiko** [JordanOsterberg/JScoreboards#1]
A majority of minigames servers are still running on older version like 1.8.
Is there any plan to backport this lib?
Sorry if this isn't the place to ask, great library anyway! 🙂

**Comment by Cosmiiko** [comment]
Woops! My bad, did not see the 1.8 branch.
Keep on the great work

**Comment by JordanOsterberg** [comment]
> A majority of minigames servers are still running on older version like 1.8.
> Is there any plan to backport this lib?
> Sorry if this isn't the place to ask, great library anyway! 🙂

1.8 support is now available in the master branch- please report any bugs as they come up!

**Comment by Cosmiiko** [comment]
Will do!
