### ISSUE TITLE
Dynamically update scoreboard

### ISSUE THREAD

**Issue by Plugner** [JordanOsterberg/JScoreboards#15]
I'm using it on my server, and I really need to update the remaining players in my minigame, I have an API that provides the player amount (excluding invisible staff and spectators), I only need to update the scoreboard every second, how can I do that?

Thanks.

**Comment by barabumjcp** [comment]
just update it when someone dies

**Comment by Plugner** [comment]
It will not update the values, but I fixed it without the library.
