### ISSUE TITLE
API can not be used with 1.8.8

### ISSUE THREAD

**Issue by CXCubeHD** [JordanOsterberg/JScoreboards#2]
I love this API but I can not use it in 1.8.8 sadly :(. It always throws the `java.lang.ClassNotFoundException` as shown  here:

`
java.lang.NoClassDefFoundError: dev/jcsoftware/jscoreboards/JPerPlayerMethodBasedScoreboard
Caused by: java.lang.ClassNotFoundException: dev.jcsoftware.jscoreboards.JPerPlayerMethodBasedScoreboard
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
        ... 17 more
`

Please make it work for 1.8.8 I would highly appriciate it :D

**Comment by Cosmiiko** [comment]
I had opened a similar issue a few days ago, but closed it after seeing that 1.8 support is already being worked on, see [this](https://github.com/JordanOsterberg/JScoreboards/tree/feature/1.8-support) branch.

**Comment by CXCubeHD** [comment]
Ah didn't know, thank you for telling though

**Comment by JordanOsterberg** [comment]
> I love this API but I can not use it in 1.8.8 sadly :(. It always throws the `java.lang.ClassNotFoundException` as shown here:
> 
> `java.lang.NoClassDefFoundError: dev/jcsoftware/jscoreboards/JPerPlayerMethodBasedScoreboard Caused by: java.lang.ClassNotFoundException: dev.jcsoftware.jscoreboards.JPerPlayerMethodBasedScoreboard at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_291] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-db6de12-18fbb24] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-db6de12-18fbb24] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291] ... 17 more`
> 
> Please make it work for 1.8.8 I would highly appriciate it :D

Firstly- the issue you're describing here isn't related to a lack of 1.8 support, it looks like an issue around not shading the library into your plugin jar.

Secondly- 1.8 support is now live on the master branch. Let me know if you hit any issues!
