### ISSUE TITLE
I can't shade API into my plugin

### ISSUE THREAD

**Issue by vitya0717** [JordanOsterberg/JScoreboards#3]
I got this error
java.lang.NoClassDefFoundError: dev/jcsoftware/jscoreboards/JGlobalScoreboard

![image](https://user-images.githubusercontent.com/50296138/128346332-ae0feb94-6588-4f74-a1e7-1c2b9ac619dd.png)

Please help me :( I need your API, but I never use maven. :/

**Comment by JordanOsterberg** [comment]
Hello,

I know this issue is closed, but I figured I would forward this message regardless:

This was resolved in version 2.1.1-RELEASE. Please update your project accordingly and reopen the issue if it hasn't been fixed properly.

**Comment by vitya0717** [comment]
Thank you for your answer! I was fix this issue then, just needed to update shade plugin to snapshot version, which is support java 16!  :)
