### ISSUE TITLE
502 Bad Gateway for dev.jcsoftware:JScoreboards:pom:2.1.1-RELEASE

### ISSUE THREAD

**Issue by leKlip** [JordanOsterberg/JScoreboards#6]
Could not transfer artifact dev.jcsoftware:JScoreboards:pom:2.1.1-RELEASE from/to jordanosterberg-repo (https://nexus-repo.jordanosterberg.com/repository/maven-releases/): Transfer failed for https://nexus-repo.jordanosterberg.com/repository/maven-releases/dev/jcsoftware/JScoreboards/2.1.1-RELEASE/JScoreboards-2.1.1-RELEASE.pom 502 Bad Gateway

**Comment by JordanOsterberg** [comment]
Please provide a more descriptive error and steps that can be taken to reproduce the issue. Additionally- have you tried different network configurations? (VPN, other wifi networks, etc) Thanks!
