### ISSUE TITLE
Minecraft Team Issue

### ISSUE THREAD

**Issue by ManojTGN** [JordanOsterberg/JScoreboards#9]
I Have Created A Plugin With This **Scoreboard API** and I Tried To Create Minecraft Team with  `/team add blue` because I wanted to create some color team and add color to the team and add players in it and to add glow potion effect so that the team players will have the respective color glow. and after creating the team and modifying, it did nothing and it does not shows on the commandTabCompletion and instead shows something else
![2021-11-12_10 52 03](https://user-images.githubusercontent.com/42494649/141428314-03fb3446-f7ab-4322-834e-3309e76de18c.png)
but it shows correctly on the world folder (`world_name/data/scoreboard.dat`)
![scoreboard](https://user-images.githubusercontent.com/42494649/141428249-2e47cce0-36b0-4a94-8bc4-bde42eb43abd.JPG)

then I realized that the lines on the scoreboard and the team names in the tabcompletion are same! so how can I fix it! and it perfectly works on the spigot server with my same plugin without this scoreboard api

**Comment by JordanOsterberg** [comment]
You can access raw Bukkit teams via a method on JScoreboardTeam, which will allow you to make certain teams glow / modify them further.

This API is not compatible with the regular Minecraft scoreboard commands/system. Closing this issue.
